# Generated by Django 5.0 on 2024-01-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_admission',
            field=models.IntegerField(),
        ),
    ]
