# Generated by Django 5.0 on 2024-02-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture_Session',
            fields=[
                ('session_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('subject_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
                ('date', models.DateField(blank=True, null=True)),
                ('stud_div', models.CharField(blank=True, max_length=1)),
                ('machine_id', models.CharField(default='N.A', max_length=250)),
                ('branch', models.CharField(max_length=250)),
            ],
        ),
    ]
