# Generated by Django 5.0 on 2024-02-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_session',
            name='stud_div',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
