# Generated by Django 5.0 on 2024-02-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec_session', '0002_lecture_session_stud_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_session',
            name='machine_id',
            field=models.CharField(default='N.A', max_length=250),
        ),
    ]
