# Generated by Django 5.0 on 2024-02-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec_session', '0003_lecture_session_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_session',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
