# Generated by Django 5.0 on 2024-02-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec_session', '0004_alter_lecture_session_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_session',
            name='branch',
            field=models.CharField(max_length=200),
        ),
    ]
