# Generated by Django 5.0 on 2024-03-10 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_table',
            name='admission_year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AddField(
            model_name='attendance_table',
            name='branch',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
