# Generated by Django 5.0 on 2024-02-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_table',
            fields=[
                ('date', models.DateField(blank=True, null=True)),
                ('in_time', models.TimeField(default='00:00:00')),
                ('is_present', models.BooleanField(default=False)),
                ('roll_no', models.CharField(max_length=250, unique=True)),
                ('session_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=100)),
                ('sem_type', models.BooleanField(default=False)),
            ],
        ),
    ]
