# Generated by Django 5.0 on 2024-02-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_table',
            name='in_time',
        ),
    ]
