# Generated by Django 5.0 on 2024-05-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_attendance_table_stud_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance_table",
            name="stud_div",
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
